from abc import ABC, abstractmethod
from typing import Any, List, Optional
from google import genai
from google.genai import types

async def reduce_voting(
    client: genai.Client,
    fallback_model: str,
    prompt: str,
    outputs: List[str],
    response_schema: Optional[Any] = None,
    reducer_model: Optional[str] = None,
    output_language: Optional[str] = None,
    **kwargs
) -> Any:
    """
    Pure function to reduce parallel model outputs by resolving consensus and majority vote.

    Args:
        client: The google-genai Client instance.
        fallback_model: The base model name to use if reducer_model is None.
        prompt: The original prompt submitted by the user.
        outputs: List of raw text outputs generated by the parallel base models.
        response_schema: Optional response schema (e.g., Pydantic model) for structured output.
        reducer_model: Optional specific model to perform the reduction step.
        output_language: Optional target language for the final output (e.g., 'Japanese', 'English').
        **kwargs: Extra parameters passed to the model generate_content call.
    """
    model_name = reducer_model or fallback_model
    candidates_str = "\n".join(
        f"Candidate {i + 1}:\n{out}\n---" for i, out in enumerate(outputs)
    )
    
    system_instruction = (
        "You are an expert consensus validator. You will be given an original prompt and a list of candidate answers "
        "generated by multiple models with different settings. Analyze these candidates, determine the consensus "
        "or majority vote, and output the final consolidated correct response."
    )
    if output_language is not None:
        system_instruction += f" You MUST generate the final output in the following language: {output_language}."
    
    user_content = (
        f"Original Prompt: {prompt}\n\n"
        f"Candidate Answers:\n{candidates_str}\n\n"
        "Please resolve the consensus and output the correct majority vote."
    )
    
    base_config = kwargs.get("config")
    config_params = {}
    if base_config is not None:
        if isinstance(base_config, dict):
            config_params = base_config.copy()
        elif hasattr(base_config, "model_dump"):
            config_params = base_config.model_dump(exclude_none=True)
        else:
            config_params = {k: getattr(base_config, k) for k in dir(base_config) if not k.startswith("_") and getattr(base_config, k) is not None}
    
    config_params["system_instruction"] = system_instruction
    config_params["temperature"] = 0.0
    
    if response_schema is not None:
        config_params["response_schema"] = response_schema
        config_params["response_mime_type"] = "application/json"
        
    config = types.GenerateContentConfig(**config_params)
    
    response = await client.aio.models.generate_content(
        model=model_name,
        contents=user_content,
        config=config
    )
    return response


async def reduce_critic(
    client: genai.Client,
    fallback_model: str,
    prompt: str,
    outputs: List[str],
    response_schema: Optional[Any] = None,
    reducer_model: Optional[str] = None,
    output_language: Optional[str] = None,
    **kwargs
) -> Any:
    """
    Pure function to reduce parallel model outputs by critically synthesizing them
    and eliminating hallucinations.

    Args:
        client: The google-genai Client instance.
        fallback_model: The base model name to use if reducer_model is None.
        prompt: The original prompt submitted by the user.
        outputs: List of raw text outputs generated by the parallel base models.
        response_schema: Optional response schema (e.g., Pydantic model) for structured output.
        reducer_model: Optional specific model to perform the reduction step.
        output_language: Optional target language for the final output (e.g., 'Japanese', 'English').
        **kwargs: Extra parameters passed to the model generate_content call.
    """
    model_name = reducer_model or fallback_model
    candidates_str = "\n".join(
        f"Candidate Answer {i + 1}:\n{out}\n---" for i, out in enumerate(outputs)
    )
    
    system_instruction = (
        "You are a critical synthesizer. You will be given an original prompt and a list of candidate answers "
        "generated by different models. Your job is to critically review these candidates, detect and eliminate "
        "any hallucinations, errors, or inconsistencies, and synthesize a single, highly accurate, and comprehensive response."
    )
    if output_language is not None:
        system_instruction += f" You MUST generate the final output in the following language: {output_language}."
    
    user_content = (
        f"Original Prompt: {prompt}\n\n"
        f"Candidate Answers:\n{candidates_str}\n\n"
        "Analyze and synthesize the final answer."
    )
    
    base_config = kwargs.get("config")
    config_params = {}
    if base_config is not None:
        if isinstance(base_config, dict):
            config_params = base_config.copy()
        elif hasattr(base_config, "model_dump"):
            config_params = base_config.model_dump(exclude_none=True)
        else:
            config_params = {k: getattr(base_config, k) for k in dir(base_config) if not k.startswith("_") and getattr(base_config, k) is not None}
    
    config_params["system_instruction"] = system_instruction
    config_params["temperature"] = 0.0
    
    if response_schema is not None:
        config_params["response_schema"] = response_schema
        config_params["response_mime_type"] = "application/json"
        
    config = types.GenerateContentConfig(**config_params)
    
    response = await client.aio.models.generate_content(
        model=model_name,
        contents=user_content,
        config=config
    )
    return response


# --- Compatibility Wrappers ---

class BaseReducer(ABC):
    """
    Abstract base class compatibility wrapper.
    """
    def __init__(self, reducer_model: Optional[str] = None):
        self.reducer_model = reducer_model

    @abstractmethod
    async def reduce(
        self,
        client: genai.Client,
        fallback_model: str,
        prompt: str,
        outputs: List[str],
        response_schema: Optional[Any] = None,
        output_language: Optional[str] = None,
        **kwargs
    ) -> Any:
        pass


class VotingReducer(BaseReducer):
    """
    Voting Reducer compatibility wrapper class.
    """
    async def reduce(
        self,
        client: genai.Client,
        fallback_model: str,
        prompt: str,
        outputs: List[str],
        response_schema: Optional[Any] = None,
        output_language: Optional[str] = None,
        **kwargs
    ) -> Any:
        return await reduce_voting(
            client=client,
            fallback_model=fallback_model,
            prompt=prompt,
            outputs=outputs,
            response_schema=response_schema,
            reducer_model=self.reducer_model,
            output_language=output_language,
            **kwargs
        )


class CriticReducer(BaseReducer):
    """
    Critic Reducer compatibility wrapper class.
    """
    async def reduce(
        self,
        client: genai.Client,
        fallback_model: str,
        prompt: str,
        outputs: List[str],
        response_schema: Optional[Any] = None,
        output_language: Optional[str] = None,
        **kwargs
    ) -> Any:
        return await reduce_critic(
            client=client,
            fallback_model=fallback_model,
            prompt=prompt,
            outputs=outputs,
            response_schema=response_schema,
            reducer_model=self.reducer_model,
            output_language=output_language,
            **kwargs
        )
