from abc import ABC, abstractmethod
from typing import Any, List, Optional
from google import genai
from google.genai import types

class BaseReducer(ABC):
    """
    Abstract base class for all ensemble reduction strategies.
    
    Attributes:
        reducer_model: The model to be used for the reduction step.
                       If None, the fallback (base) model will be used.
    """
    def __init__(self, reducer_model: Optional[str] = None):
        self.reducer_model = reducer_model

    @abstractmethod
    async def reduce(
        self,
        client: genai.Client,
        fallback_model: str,
        prompt: str,
        outputs: List[str],
        response_schema: Optional[Any] = None,
        **kwargs
    ) -> Any:
        """
        Reduce the parallel model outputs into a single consolidated response.

        Args:
            client: The google-genai Client instance.
            fallback_model: The base model name to use if self.reducer_model is None.
            prompt: The original prompt submitted by the user.
            outputs: List of raw text outputs generated by the parallel base models.
            response_schema: Optional response schema (e.g., Pydantic model) for structured output.
            **kwargs: Extra parameters passed to the model generate call.
        """
        pass


class VotingReducer(BaseReducer):
    """
    Voting Reducer designed for classification or structured output tasks.
    It takes the parallel outputs and uses the reducer_model to determine
    the consensus or majority vote, parsing it according to the schema if provided.
    """
    async def reduce(
        self,
        client: genai.Client,
        fallback_model: str,
        prompt: str,
        outputs: List[str],
        response_schema: Optional[Any] = None,
        **kwargs
    ) -> Any:
        model_name = self.reducer_model or fallback_model
        
        # Prepare the list of candidates to present to the reducer model
        candidates_str = "\n".join(
            f"Candidate {i + 1}:\n{out}\n---" for i, out in enumerate(outputs)
        )
        
        system_instruction = (
            "You are an expert consensus validator. You will be given an original prompt and a list of candidate answers "
            "generated by multiple models with different settings. Analyze these candidates, determine the consensus "
            "or majority vote, and output the final consolidated correct response."
        )
        
        user_content = (
            f"Original Prompt: {prompt}\n\n"
            f"Candidate Answers:\n{candidates_str}\n\n"
            "Please resolve the consensus and output the correct majority vote."
        )
        
        # Reconstruct base config from kwargs if present
        base_config = kwargs.get("config")
        config_params = {}
        if base_config is not None:
            if isinstance(base_config, dict):
                config_params = base_config.copy()
            elif hasattr(base_config, "model_dump"):
                config_params = base_config.model_dump(exclude_none=True)
            else:
                config_params = {k: getattr(base_config, k) for k in dir(base_config) if not k.startswith("_") and getattr(base_config, k) is not None}
        
        config_params["system_instruction"] = system_instruction
        config_params["temperature"] = 0.0  # Fixed to 0.0 to ensure deterministic/strict voting results
        
        if response_schema is not None:
            config_params["response_schema"] = response_schema
            config_params["response_mime_type"] = "application/json"
            
        config = types.GenerateContentConfig(**config_params)
        
        response = await client.aio.models.generate_content(
            model=model_name,
            contents=user_content,
            config=config
        )
        return response


class CriticReducer(BaseReducer):
    """
    Critic Reducer designed for creative writing, synthesis, or reasoning tasks.
    It aggregates parallel outputs and uses the reducer_model to critically review
    them, eliminate any hallucinations or inconsistencies, and synthesize a single answer.
    """
    async def reduce(
        self,
        client: genai.Client,
        fallback_model: str,
        prompt: str,
        outputs: List[str],
        response_schema: Optional[Any] = None,
        **kwargs
    ) -> Any:
        model_name = self.reducer_model or fallback_model
        
        # Prepare the list of candidates to present to the reducer model
        candidates_str = "\n".join(
            f"Candidate Answer {i + 1}:\n{out}\n---" for i, out in enumerate(outputs)
        )
        
        system_instruction = (
            "You are a critical synthesizer. You will be given an original prompt and a list of candidate answers "
            "generated by different models. Your job is to critically review these candidates, detect and eliminate "
            "any hallucinations, errors, or inconsistencies, and synthesize a single, highly accurate, and comprehensive response."
        )
        
        user_content = (
            f"Original Prompt: {prompt}\n\n"
            f"Candidate Answers:\n{candidates_str}\n\n"
            "Analyze and synthesize the final answer."
        )
        
        # Reconstruct base config from kwargs if present
        base_config = kwargs.get("config")
        config_params = {}
        if base_config is not None:
            if isinstance(base_config, dict):
                config_params = base_config.copy()
            elif hasattr(base_config, "model_dump"):
                config_params = base_config.model_dump(exclude_none=True)
            else:
                config_params = {k: getattr(base_config, k) for k in dir(base_config) if not k.startswith("_") and getattr(base_config, k) is not None}
        
        config_params["system_instruction"] = system_instruction
        config_params["temperature"] = 0.0  # Strictness requirement
        
        if response_schema is not None:
            config_params["response_schema"] = response_schema
            config_params["response_mime_type"] = "application/json"
            
        config = types.GenerateContentConfig(**config_params)
        
        response = await client.aio.models.generate_content(
            model=model_name,
            contents=user_content,
            config=config
        )
        return response
